#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   localhost resolves to 127.0.0.2
#   facebook.com resolves to 8.8.8.8.

if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root."
  exit 1
fi

cp /etc/hosts /etc/hosts.bak

# Modifying the hosts file
sed -i 's/^127.0.0.1[[:space:]]*localhost/127.0.0.2 localhost/g' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Configuration completed."
